name: defected_log_app
description: "A new Flutter project."
publish_to: "CCP IRQ"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  sqflite_common_ffi: ^2.2.1
  sqflite: ^2.2.8
  path: ^1.8.3
  flutter_svg: ^2.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  fl_chart: ^0.63.0
  file_picker: ^8.3.1
  window_size: ^0.1.0
  bcrypt: ^1.1.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  windows:
    generate: true
    image_path: "lib/assets/logo.png"
    icon_size: 100

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/assets/my_logo.ico
    - lib/assets/background.jpg
